### ISSUE TITLE
define and implement use case for Payone Vorkasse

### ISSUE THREAD

**Issue by floriansattler** [commercetools/commercetools-sunrise-java-payment#15]
define what happens when, where and how if the user selects Payone Vorkasse as his payment method

**Comment by floriansattler** [comment]
data and user action flow needs to be implemented as following:

user selects "Vorkasse" as his payment method
PaymentFramework creates Payment object @ CTP (success, cancel, error redirect URLs provided by the shop)
shop shows "buy now" button, user clicks it
create the transaction
call the "handlePayment" method of the Payone Connector
interpret the result -> get a valid payment object back
possibly a redirect URL is provided -> then redirect
handle callbacks after redirect accordingly
create order if everything worked fine
show confirmation page
cancel or error callbacks have to be handled by the shop and should probably result in the possibility to select a new payment method

**Comment by MGA-dotSource** [comment]
@floriansattler  what kind of redirectURL could be provided after the "handle" call?
if so, is its existence a marker for error or for success?

**Comment by mht-dotsource** [comment]
"Vorkasse" does not use redirect urls.

**Comment by butenkor** [comment]
@floriansattler can it be closed?

**Comment by floriansattler** [comment]
@mht-dotsource can you please have a look if the description in this issue is correct, or if it needs to be adjusted to the way you implemented it?

**Comment by mht-dotsource** [comment]
data and user action flow needs to be implemented as following:

1. user selects "Vorkasse" as his payment method
2. PaymentFramework creates Payment object @ CTP
3. shop shows "buy now" button, user clicks it
4. create the transaction
5. call the "handlePayment" method of the Payone Connector
6. interpret the result -> get a valid payment object back
7. create order if everything worked fine
8. show confirmation page (confirmation page should contain bank information so that the customer knows to which bank he has to transfer the money.

there are no redirect and therefore no success/cancel/error-urls
